defmodule CodeLeadWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :code_lead

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_code_lead_key",
    signing_salt: "N99trAN9",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Preview subdomains (task-<id>.<PREVIEW_DOMAIN>, subdomain gateway
  # only) divert here before anything else in the pipeline — sockets,
  # Plug.Static, and the parsers must not see proxied traffic: the
  # previewed app's own /live socket or /assets/* would otherwise be
  # answered by CodeLead instead of forwarded. Phoenix's generated
  # wrapper still runs outside this override, so `secret_key_base` and
  # error rendering are already in place. No-op (nil match) unless
  # PREVIEW_DOMAIN is configured.
  def call(conn, opts) do
    case CodeLeadWeb.PreviewHost.match(conn.host) do
      nil -> super(conn, opts)
      task_id -> CodeLeadWeb.PreviewHost.call(conn, task_id)
    end
  end

  @doc """
  The session cookie configuration, for the preview host's session
  (same store and salts, its own cookie name).
  """
  def session_options, do: @session_options

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :code_lead,
    gzip: not code_reloading?,
    only: CodeLeadWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :code_lead
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Plug.Parsers behind a wrapper: /preview/* bodies must reach the
  # reverse proxy unread so they can be forwarded byte-for-byte.
  plug CodeLeadWeb.Plugs.PreviewAwareParsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug CodeLeadWeb.Router
end
